spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ceramic?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=miSuperSecretoJwtClave1234567890123456
jwt.expiration=86400000

perudevs.api.key=cGVydWRldnMucHJvZHVjdGlvbi5maXRjb2RlcnMuNjcyY2UyZTg5ZmE0MTczZjYxMzIwNDZi
perudevs.api.url=https://api.perudevs.com/api/v1/dni/complete

google.auth.client-id=681148510104-sirb6klrba5ia7g0ak58qlfc9do9uh7k.apps.googleusercontent.com
google.auth.token-info-url=https://oauth2.googleapis.com/tokeninfo

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=efrainqn16@gmail.com
spring.mail.password=mwbxsjkldnnkatlu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000 