spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/ceramic_store_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=miSuperSecretoJwtClave1234567890123456
jwt.expiration=86400000
